# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jaxai',
                'doc_host': 'https://fredguth.github.io',
                'git_url': 'https://github.com/fredguth/jaxai',
                'lib_path': 'jaxai'},
  'syms': {'jaxai.core': {'jaxai.core.foo': ('core.html#foo', 'jaxai/core.py')}}}
